name: Deploy web app
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
      - 'development'
jobs:
  ci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: laravel-pint
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true
          configPath: "vendor/my-company/coding-style/pint.json"
          pintVersion: 1.8.0
          onlyDirty: true

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: cache-pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: install-pre-commit
        run: pip3 install pre-commit

      - name: run-pre-commit
        shell: bash
        run: |
          pre-commit run  --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }} --show-diff-on-failure --color always
