name: Deploy web app with vapor
on:
  workflow_call:
    inputs:
      DEPLOY_ENVIRONMENT:
        required: true
        type: string
      PHP_VERSION:
        required: true
        type: string 
    secrets:
      VAPOR_API_TOKEN:
        required: true
jobs:
  ci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: laravel-pint
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true
          configPath: "vendor/my-company/coding-style/pint.json"
          pintVersion: 1.8.0
          onlyDirty: true

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: cache-pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: install-pre-commit
        run: pip3 install pre-commit

      - name: run-pre-commit
        shell: bash
        run: |
          pre-commit run  --all-files --show-diff-on-failure --color always

  deploy:
    runs-on: ubuntu-latest
    needs: [ci-lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup_php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
          tools: composer:v2
          coverage: none

      - name: install-vapor-cli
        run: composer global require laravel/vapor-cli

      - name: insall-composer-deps
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: deploy-${{inputs.DEPLOY_ENVIRONMENT }}
        env:
            VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
        run: |
          vapor deploy ${{ inputs.DEPLOY_ENVIRONMENT }}
